WebViewAssetLoader support
react-native-webview/react-native-webview pull request #1616
Opened 2020-09-06 12:19 UTC by duxiaofeng-github

# Summary

i need to access my local asset, a html file, over https. because some of my js code require [Secure_Contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), so i can't access that html by **file:///** protocol.

android x provide a new lib **WebViewAssetLoader** to achieve this goal. [more detail](https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader).

there is a [example](https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/webkit/integration-tests/testapp/src/main/java/com/example/androidx/webkit/AssetLoaderAjaxActivity.java) code on android source code to show how we can use WebViewAssetLoader.

---

according to androidx.webkit's [doc](https://developer.android.com/reference/androidx/webkit/package-summary), the **minimum sdk version** to use this library is 14. react-native-webview is 16, so the requirement is fit.

finally we need to add an dependency for build.gradle

```
dependencies {
    implementation 'androidx.webkit:webkit:1.2.0'
}
```

## Test Plan

according to this [doc](https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader), after apply WebViewAssetLoader, we can access assets by **https://appassets.androidplatform.net/assets/some-assets** now.

## Compatibility

there is nothing need to do with other platforms

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌    |
| Android |    ✅    |

## Checklist

- [ x ] I have tested this on a device and a simulator
- [ x ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

2020-09-13 01:56 UTC, TheAlmightyBob requested changes
This looks good to have support for, but could you make it configurable? In apps where the devs don't have full control of the content being loaded in the WebView, I could imagine it being undesirable that a page could link to `https://appassets.androidplatform.net` to make the WebView unexpectedly display random app assets?
(it would probably be _ideal_ to expose full configuration of domain URL, supported paths, etc, but for the purpose of this PR I think just having the feature disabled by default and a property to enable would be good)

Does iOS not have this problem with Secure Contexts and "file://", or are you just not using iOS?

2020-09-13 01:56 UTC, TheAlmightyBob commented on docs/Guide.md
> +Android x provide a new way to access assets, by using WebViewAssetLoader. now we can access assets via uri **https://appassets.androidplatform.net/assets/some-assets**
nit: I think it should be "Android X"?

2020-09-13 08:05 UTC, duxiaofeng-github commented on docs/Guide.md
> +Android x provide a new way to access assets, by using WebViewAssetLoader. now we can access assets via uri **https://appassets.androidplatform.net/assets/some-assets**
😂

2020-09-13 08:18 UTC, duxiaofeng-github commented
ok, i'll make it configurable.

> Does iOS not have this problem with Secure Contexts and "file://", or are you just not using iOS

Secure context is supported by "file://" protocol of iOS by default. so we don't need to do any magic for it.

2020-11-20 00:30 UTC, closed without merging

2021-11-17 14:11 UTC, mlecoq commented
Hi, I would like to user WebAssetLoader, could this be merged ?