Fix onScroll event type
react-native-webview/react-native-webview pull request #1631
Opened 2020-09-10 23:00 UTC by Hazeman27

# Summary

Fixes type of the event of the `onScroll` function.

Issue: #1627

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md` **(Didn't find `CHANGELOG.md` in the repo)**
- [X] I updated the typed files (TS and Flow)
- [X] I added a sample use of the API in the example project (`example/App.js`) **(Example already existed)**

2020-09-13 19:54 UTC, TheAlmightyBob requested changes
Looks good, just one small comment on the docs (thanks for adding documentation though!)

2020-09-13 19:54 UTC, TheAlmightyBob commented on docs/Reference.md
> +type as an argument.
The documentation for other events also lists the properties of the native event. Could you add that?

2020-09-22 22:09 UTC, TheAlmightyBob approved these changes

2020-11-10 08:32 UTC, Hazeman27 commented
Still waiting for review and merge 😢

2020-12-05 18:59 UTC, TheAlmightyBob commented
@jamonholmgren @Titozzz This seems like a straightforward types/documentation fix :)

2020-12-05 19:29 UTC, Titozzz approved these changes

2020-12-05 19:29 UTC, merged

2020-12-05 19:30 UTC, Titozzz commented
> Still waiting for review and merge 😢

Sorry 😭