Cookie sync improvements
react-native-webview/react-native-webview pull request #2535
Opened 2022-06-09 12:46 UTC by matiaskorhonen

Use a `WKHTTPCookieStoreObserver` to sync the cookies from the webview to `NSHTTPCookieStorage`.

Most developers shouldn't notice any difference in behaviour but based on my testing this seems to be more reliable than the old way where the cookies were synced in the `didFinishNavigation` callback.

2022-06-22 10:05 UTC, matiaskorhonen commented
FYI, rebased against master now, @TheAlmightyBob & @Titozzz

2022-06-22 19:10 UTC, TheAlmightyBob commented
Can you explain any more about what unreliability or race conditions you were experiencing that this addresses?

2022-06-23 06:57 UTC, matiaskorhonen commented
Essentially rapid changes to the cookies inside the WebView would cause the NSHTTPCookieStorage to go out of sync resulting in authentication errors. Switching to this observer based approach fixed the issue for us.

2022-08-15 16:17 UTC, allan-simon commented
@matiaskorhonen  do you think it relates to one of these issues ? https://github.com/react-native-webview/react-native-webview/issues/1780  and/or https://github.com/react-native-webview/react-native-webview/issues/2228 ? (our app also has issue with session stored in cookie so any improvement on that side is more than welcomed :) )

2022-08-19 10:12 UTC, matiaskorhonen commented
> do you think it relates to one of these issues ? #1780 and/or #2228

Possibly, though I can't be sure as we mostly rely on the sync working *from* the webview to the shared cookie store (and not the other way around). 

I can say that the patch in this PR has improved the reliability of the cookie sync in our production app…

2022-08-19 21:19 UTC, allan-simon commented on apple/RNCWebView.m
> -
shouldn't the PR  don't touch extra whitespace to ease the size of the diff and increase chance of it being merged ?

2022-10-10 07:21 UTC, allan-simon commented on apple/RNCWebView.m
> -
@matiaskorhonen  ping ? I think removing the extra whitespace change will increase a lot the chance of it being reviewed/merged

2022-11-17 12:42 UTC, allan-simon commented
@TheAlmightyBob did you get time to review this, now that the diff is much much shorter ? :angel:

2022-11-17 18:47 UTC, TheAlmightyBob requested changes
Sorry for the delay, I was hoping that somebody with better understanding of cookies would review, but you're right that it's at least not a big change :)

2022-11-17 18:47 UTC, TheAlmightyBob commented on apple/RNCWebView.m
> -      [self syncCookiesToWebView:nil];
Did you mean to remove the `syncCookiesToWebView` call here? That's not equivalent to the `addObserver` line

2022-11-23 00:23 UTC, TheAlmightyBob approved these changes

2022-11-23 01:03 UTC, merged