feat(iOS): fraudulent website warning setting
react-native-webview/react-native-webview pull request #2801
Opened 2023-01-10 04:57 UTC by sunnylqm

2023-01-10 23:15 UTC, TheAlmightyBob requested changes
Just minor typos, otherwise looks good. Note that you should expect a delay before this gets merged (and there might be conflicts to resolve), as there are some other things in the queue first.

2023-01-10 23:15 UTC, TheAlmightyBob commented on docs/Reference.md
> +A Boolean value that indicates whether the web view shows warnings for suspected fraudulent content, such as malware or phishing attemps. The default value is `true`. (iOS 13+)
nit:
```suggestion
A Boolean value that indicates whether the web view shows warnings for suspected fraudulent content, such as malware or phishing attempts. The default value is `true`. (iOS 13+)
```

2023-01-10 23:15 UTC, TheAlmightyBob commented on src/WebViewTypes.ts
> +   * fraudulent content, such as malware or phishing attemps.
nit:
```suggestion
   * fraudulent content, such as malware or phishing attempts.
```

2023-01-11 06:21 UTC, TheAlmightyBob approved these changes

2023-03-13 00:56 UTC, TheAlmightyBob commented
'sup bot, please keep open

2023-06-10 18:11 UTC, closed without merging

2023-06-10 18:12 UTC, Titozzz commented
closing for #2994