Add Blob downloading feature (Android)
react-native-webview/react-native-webview pull request #3022
Opened 2023-06-26 03:31 UTC by devmuhnnad

This fixes #2951, #2526, #2207, #1945, #1790, #909, #295 and #2526

I have tested the feature on a React native project, and it worked perfectly 🌟

### Usage

```jsx
function App(): JSX.Element {
  return <WebView blobDownloadingEnabled={true} source={{uri: 'https://pdfturn.com/'}} />;
}
```

For security purposes, the Blob Downloading Feature is not enabled by default, ``blobDownloadingEnabled`` prop is used.

### Is this a Break Change
No, I have developed this feature to be independent, not effecting others.

THANKS.

2023-06-29 03:30 UTC, WANG-Lisa commented
I tried branch code of blob-download-feature in react-native-webview repo, when download blob, it shows error
"Refused to connect to 'blob:xxxxx" because it violates the following Content Security Policy directive: "default-src ". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback. Note that '' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches self's scheme. The scheme 'blob:' must be added explicitly.

I hope this issue can be fixed in blob-download-feature PR.

2023-06-29 17:21 UTC, devmuhnnad commented
Hi @WANG-Lisa, thanks for reporting this, 
can you provide more information about how you tested the feature, is it on Android? Did you make sure that the ``blobDownloadingEnabled`` prop was set to true?

Also if you can provide a repo with the project you have faced the issue with, that would be helpful,

Thanks.

2023-06-30 02:24 UTC, WANG-Lisa commented
> Hi @WANG-Lisa, thanks for reporting this, can you provide more information about how you tested the feature, is it on Android? Did you make sure that the `blobDownloadingEnabled` prop was set to true?
> 
> Also if you can provide a repo with the project you have faced the issue with, that would be helpful,
> 
> Thanks.

@devmuhnnad Thanks for your quick response.
I install `blob-download-feature` branch in my package.json, my webview is something like this
`<WebView
	source={{ uri: 'blob:https://xxx' }}
	startInLoadingState={true}
	javaScriptEnabled
        blobDownloadingEnabled
        allowFileAccess
        domStorageEnabled
        mixedContentMode='always'
        allowUniversalAccessFromFileURLs
	renderLoading={() => (
	<ActivityIndicator
		style={styles.indicator}
		size='large'
	/>
	)}
	onMessage={handleMessage}
	originWhitelist={['https:*', 'blob:*']}
/>`
I test it on android simulator, here is the info of simulator
![image](https://github.com/react-native-webview/react-native-webview/assets/69227445/ba01d38a-91f8-4185-bd18-d9aef9f64bc0)
in logcat, it print this error: `"Refused to connect to 'blob:xxxxx" because it violates the following Content Security Policy directive: "default-src ". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback. Note that '' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches self's scheme. The scheme 'blob:' must be added explicitly.`

2023-06-30 07:53 UTC, devmuhnnad commented
Hi @WANG-Lisa, I see that you are using the source prop wrong!
You should pass a valid URL that starts with "http" or "https",
I think that there's a misunderstanding about ``blob-download-feature``
it allows you to download blobs when a trigger occurs, 
like clicking on a button on the website you are using the Webview for.

2023-06-30 08:35 UTC, WANG-Lisa commented
> 



> Hi @WANG-Lisa, I see that you are using the source prop wrong! You should pass a valid URL that starts with "http" or "https", I think that there's a misunderstanding about `blob-download-feature` it allows you to download blobs when a trigger occurs, like clicking on a button on the website you are using the Webview for.

My fault to this misunderstanding. Actually my case is what you indicate. I load an https page in webview, then in this https page, I want to download a pdf which type is blob. Once I click the download button, it shows Content Security Policy  error.

2023-06-30 08:53 UTC, devmuhnnad commented
@WANG-Lisa it would help if you share with me a repo of your project

2023-07-03 05:18 UTC, WANG-Lisa commented
> @WANG-Lisa it would help if you share with me a repo of your project

As the repo is confidential, I can't share it out. However, I find that if the blob is of type pdf or csv, it will show the error I indicate, others like 'application/json', it's ok to donwload.

2023-07-03 06:46 UTC, devmuhnnad commented
@WANG-Lisa I understand.
I have tried with pdf blobs, and it worked! 
I can't reproduce your issue.

2023-07-04 02:30 UTC, WANG-Lisa commented
I'll try to reintegrate after this PR is merged. Looking forward to this feature to be released asap.
Thanks @devmuhnnad for your help anyway.
<iframe src="https://giphy.com/embed/7YyKEY3KvvmPfpKPfz" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/7YyKEY3KvvmPfpKPfz">via GIPHY</a></p>

2023-07-07 12:38 UTC, rootedy-ffit commented
Hi @devmuhnnad, can you help me? I tried to install from this PR with yarn:
`yarn add react-native-webview/react-native-webview#blob-download-feature`
But when I run i got this error:
`Error: Unable to resolve module ./lib/WebView`
And the folder "./lib" really doesn't exist. How can I use this PR?

2023-07-16 22:40 UTC, TheAlmightyBob requested changes

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
> +            }
I think this should only be executed if the feature is enabled?

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
> +
```suggestion
```

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
> +
```suggestion
```

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
> +
```suggestion
```

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
> +    }
This looks unused

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
> +  class RNCWebViewBridge internal constructor() {
What's the difference between this and `RNCWebViewDownloadBridge`?

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
> +        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.KITKAT) {
I don't think React Native supports versions older than Kit Kat

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManagerImpl.kt
> +    view.setDownloadingMessage(getDownloadingMessageOrDefault())
It seems like you wanted a "downloaded" message, not the "downloading" message that `getDownloadingMessageOrDefault` is tied to...?

2023-07-16 22:40 UTC, TheAlmightyBob commented on src/WebView.android.tsx
> +  const { onLoadingStart,  onShouldStartLoadWithRequest, onMessage, viewState, setViewState, lastErrorEvent, onHttpError, onLoadingError, onLoadingFinish, onLoadingProgress, onRenderProcessGone } = u
```suggestion
  const { onLoadingStart, onShouldStartLoadWithRequest, onMessage, viewState, setViewState, lastErrorEvent, onHttpError, onLoadingError, onLoadingFinish, onLoadingProgress, onRenderProcessGone } = useWebViewLogic({
```

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/assets/blobDownloader.js
> +// This is used because download from native side won't have session changes.
I'm not sure what what this means about "session changes"?

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/assets/blobDownloader.js
> +    let fileName = "";
```suggestion
    reader.readAsDataURL(blob);
    
    let fileName = "";
```

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/assets/blobDownloader.js
> +
```suggestion

```

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/assets/blobDownloader.js
> +    const popularExts = ["pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "txt", "jpg", "jpeg", "png", "gif", "bmp", "tiff", "tif", "svg", "mp3", "mp4", "avi", "mov", "wmv", "flv", "ogg", "webm",
It seems like a more accurate name would be `supportedExtensions`... but also, why only support these? Why not accept whatever extension is present?

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/assets/blobDownloader.js
> +	    ReactNativeWebViewDownloader.downloadFile(JSON.stringify(message));
```suggestion
	  ReactNativeWebViewDownloader.downloadFile(JSON.stringify(message));
```

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/assets/blobDownloader.js
> +    ext = "bin";
```suggestion
      ext = "bin";
```

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/assets/blobDownloader.js
> +
```suggestion
```

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/assets/blobDownloader.js
> +    };
```suggestion
  };
```

2023-07-16 22:40 UTC, TheAlmightyBob commented on android/src/main/assets/blobDownloader.js
> + }
```suggestion
}
```

2023-09-21 12:54 UTC, piechoo commented
@devmuhnnad Could you please take a look :) ?

2023-09-21 15:48 UTC, devmuhnnad commented on android/src/main/java/com/reactnativecommunity/webview/RNCWebView.java
> +            path.mkdirs();
This is auto format from prettier, for me I think it makes it more clear that the instruction is a block of the if statement

2023-10-04 09:06 UTC, AntoineThibi commented
Why would it be a Android only feature ? Can't it be done for iOS also ?

2023-11-22 09:06 UTC, SergioAN007 commented
Hello.
This PR still not merged? Any updates? 
Thanks

2023-12-19 17:20 UTC, Salmankhan033 commented
I got this error How to fix it.
 Please help :)
 
 WARN  Possible Unhandled Promise Rejection (id: 1):
Error: Unable to open URL: blob:https://dev.orderlemon.com/f0b9e8c6-f643-4761-a949-cc2be2c877a9

2023-12-19 18:26 UTC, Salmankhan033 commented
> Hi @devmuhnnad, can you help me? I tried to install from this PR with yarn: `yarn add react-native-webview/react-native-webview#3022/head` But when I run i got this error: `Error: Unable to resolve module ./lib/WebView` And the folder "./lib" really doesn't exist. How can I use this PR?

Go to the file and replace it by 

```
import WebView from './src/index';

export { WebView };
export default WebView;
```

2024-01-09 06:37 UTC, Sreejit7 commented
@jamonholmgren @Titozzz can this PR be merged?

2024-03-03 05:11 UTC, ainnotate commented
I've a wav file as a blob and I'll have to save/download the blob as a .wav file.

@devmuhnnad  you mentioned  we should pass a valid URL that starts with "http" or "https". Does this mean that I'll not be able to use this patch to save my wav file?

2024-03-07 15:51 UTC, linonetwo commented
@ainnotate When you create blob url it auto add HTTP to it, see https://github.com/react-native-webview/react-native-webview/issues/2858#issuecomment-1983806840

```
var link = document.createElement("a");
var blob = new Blob(["sdfa"], {type: "text/html"});
link.setAttribute("href", URL.createObjectURL(blob));
link.setAttribute("download","filename");
document.body.appendChild(link);
// <a href=​"blob:​http:​/​/​localhost/​cf8ae139-a28c-43ec-9943-86ff2e0d10d0" download=​"filename">​</a>​

link.click();
```

2024-03-19 14:04 UTC, sparcbr commented
With this will I be able to use: URL.createObjectURL(blob)  ?

2024-04-08 05:57 UTC, HiteshGit002 commented
> > Hi @devmuhnnad, can you help me? I tried to install from this PR with yarn: `yarn add react-native-webview/react-native-webview#3022/head` But when I run i got this error: `Error: Unable to resolve module ./lib/WebView` And the folder "./lib" really doesn't exist. How can I use this PR?
> 
> Go to the file and replace it by
> 
> ```
> import WebView from './src/index';
> 
> export { WebView };
> export default WebView;
> ```

just re-install node modules

2024-04-16 05:24 UTC, web-iou commented
it only works on Android?   it can be work on with ios?  @devmuhnnad

2024-05-22 10:26 UTC, raviraj-tudip commented
Hi All,

I'm encountering the same issue—I'm unable to download a PDF associated with a blob URL. This problem has been open for quite long time, and we haven't found a solution yet. Could someone please offer assistance?

2024-06-17 15:19 UTC, andrew-bierman commented
Anything I can do to help this get merged in ? Would love to use this to support blob downloads on ios and android

2024-07-16 05:31 UTC, vinayroy1 commented
i am using latest version of webview but i am not able to get above enableblobdownload props. and without that for android download working fine. but for ios its just opening document not downloading it.

2024-08-01 15:36 UTC, VariabileAleatoria commented
Please this is so much needed

2024-08-20 07:15 UTC, lhr000lhr commented
any update?

2024-09-23 02:06 UTC, long-vv commented
Hi, I have the same problem (using blob URL to download file)
When will this PR be merged? Please merge it, thanks in advance

2024-10-08 12:32 UTC, muhzain commented
Any update on this? Facing the same issue of downloading blobs on android

2024-12-15 00:22 UTC, closed without merging

2025-03-01 15:05 UTC, Kaizodo commented
Any update on this issue ? still happning 2025

2025-10-29 12:29 UTC, Sheaffy commented
This issue of blob downloading / base64 downloading, from looking back at previous issues and pull requests, this seems to have been ignored and pushed aside on multiple occasions with multiple people trying to get this fixed from different angles.

While I can't speak as I'm not directly contributing, what is going on here? Is this being missed because github-actions bot is too hasty on making requests stale, then closing them? 

From all the issues and people attempting to fix this issue, I'm surprised this is taking so long, it's been going on for years.