add inspectable property for iOS/macOS
react-native-webview/react-native-webview pull request #3075
Opened 2023-07-28 18:30 UTC by kevinvangelder

As far as I can tell this *should* work, but does not.

2023-07-30 23:23 UTC, TheAlmightyBob commented
What's the difference between this and [`webViewDebuggingEnabled`](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#webviewDebuggingEnabled)?

2023-07-31 02:24 UTC, o-alexandrov requested changes
Example is broken

2023-07-31 02:24 UTC, o-alexandrov commented on example/ios/.xcode.env
> +export NODE_BINARY=/Users/kvg/.asdf/installs/nodejs/18.16.1/bin/node
You probably want to remove this leftover

2023-07-31 13:53 UTC, kevinvangelder commented
@TheAlmightyBob I looked for an existing implementation and could not find one, thanks for pointing it out.

2023-07-31 13:54 UTC, closed without merging