Suppress menu items
react-native-webview/react-native-webview pull request #3082
Opened 2023-08-01 14:31 UTC by Arjan-Zuidema

This is a followup on https://github.com/react-native-webview/react-native-webview/pull/2845

Implemented the `suppressMenuItems` prop (iOS only) to suppress menu items from the long press context menu.

2023-08-14 01:24 UTC, TheAlmightyBob requested changes
Please update `Reference.md` (the previous PR did, but seems to have been missed here)

Also, has this been tested with the new architecture on iOS? I'm curious if anything needs to be added to `RNCWebView.mm` (it's possible it doesn't, I'm not sure)

Otherwise looks good

2023-08-23 07:17 UTC, Arjan-Zuidema commented
Hi @TheAlmightyBob I was on vacation for the past couple of weeks.

> Please update `Reference.md` (the previous PR did, but seems to have been missed here)
Yes will do this!

> 
> Also, has this been tested with the new architecture on iOS? I'm curious if anything needs to be added to `RNCWebView.mm` (it's possible it doesn't, I'm not sure)

I can't remember, will test it again at the end of the week. It seems the checks all pass on CI. Which should be sufficient?

2023-08-24 01:50 UTC, TheAlmightyBob commented
> It seems the checks all pass on CI. Which should be sufficient?

Unfortunately not, this project's CI is not quite that sophisticated. 😞

2023-08-25 09:52 UTC, Arjan-Zuidema commented
Seems like I did not test the new arch. I can't seem to `install pod` with `RCT_NEW_ARCH_ENABLED=1` Any idea how to do this? Can't seem to find anything in [Contributing.md](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Contributing.md) about this

![image](https://github.com/react-native-webview/react-native-webview/assets/30040390/0f390f78-4b61-45de-b52b-810f7368f4f4)

2023-08-25 12:59 UTC, Arjan-Zuidema commented
I got a build running with fabric enabled:
- `cd example/ios`
- `RCT_NEW_ARCH_ENABLED=1 pod install`
- `cd ../..`
- `yarn ios`

But it seems the properties are not working with fabric enabled, but without fabric it's working just fine. How do I fix this?

2023-08-25 18:47 UTC, TheAlmightyBob commented
Glad you figured out the new architecture build and good point that the Contributing doc should include instructions for that!

I can't tell you how to fix things without debugging and knowing details of what's failing (also I'm not an expert on the new architecture), but as I suggested in my previous comment, `RNCWebView.mm` may need to be updated in some form. That file is specific to the new architecture.

2023-08-25 20:33 UTC, Arjan-Zuidema commented
> Glad you figured out the new architecture build and good point that the Contributing doc should include instructions for that!

I'll make a separate pull request to update the docs, next week.
 
> I can't tell you how to fix things without debugging and knowing details of what's failing (also I'm not an expert on the new architecture), but as I suggested in my previous comment, `RNCWebView.mm` may need to be updated in some form. That file is specific to the new architecture.

I added support for fabric, it's working now. Hope this is good, I also am not expert on fabric or objective-c for that matter 😛

2023-08-25 21:32 UTC, TheAlmightyBob approved these changes

2023-08-25 21:35 UTC, TheAlmightyBob requested changes

2023-08-25 21:35 UTC, TheAlmightyBob commented on docs/Reference.md
> +Allowes to suppress menu item from the default context menu.
typo
```suggestion
Allows to suppress menu item from the default context menu.
```

2023-08-25 21:36 UTC, TheAlmightyBob approved these changes

2023-08-25 22:38 UTC, merged